site_name: Phake - PHP Mocking Framework
repo_name: "phake/phake"
repo_url: https://github.com/phake/phake
site_url: https://phake.github.io/
edit_uri: "https://github.com/phake/phake.github.io/tree/master/src"
docs_dir: src
site_dir: htdocs

site_description: |
  Modern PHP Mocking Framwork for PHP7 and PHP8.

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: " ¶"
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      auto_title: false
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: "&copy; 2022 Created and maintained by <a href=\"https://github.com/mlively\">Mike Lively</a>, <a href=\"https://github.com/bfeaver\">Brian Feaver</a> and <a href=\"https://github.com/adoy\">Pierrick Charron</a>."


theme:
  name: material
  custom_dir: theme
  logo: assets/images/phake-white.svg
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Documentation:
    - Introduction: doc/index.md
    - Creating Mocks: doc/mocks.md
    - Method Stubbing: doc/stubbing.md
    - Method Verification: doc/method-verification.md
    - Mocking Static Methods: doc/mocking-statics.md
    - Answers: doc/answers.md
    - Method Parameter Matchers: doc/method-parameter-matchers.md
    - Configuration: doc/configuration.md
    - Cookbooks:
      - doc/cookbooks/annotations.md
  - cheat-sheet.md

plugins:
  - search:
      separator: '[\s\-\.\:]'
